trigger:
  batch: true
  branches:
    include: [ master ]


schedules:
- cron: 0 12 * * 0
  displayName: weekly Sunday build
  branches:
    include: [ master ]
  always: true


pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  clean: true

- task: ComponentGovernanceComponentDetection@0
  inputs:
    verbosity: Verbose
    alertWarningLevel: Medium
    failOnAlert: true
  displayName: Component Governance ( aka.ms/cgdocs )
