site_name: My Docs

nav:
- Home: index.md
- API reference:
    constants: constants.md
    exceptions: exceptions.md
    logging: logging.md

theme:
  name: material

plugins:
- search
- mkdocstrings
