name: docs

on:
  push:
    branches:
    - main
    - dkmiller/mkdocs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9
    - name: pip install
      run: pip install -r src/requirements.txt

    - name: deploy docs
      run: mkdocs gh-deploy
      working-directory: src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
